TrajectoryPlannerROS:

  # Robot configuration parameters
  max_vel_x: 0.45
  min_vel_x: 0.1
  
  max_rotational_vel: 0.5
  min_in_place_rotational_vel: 0.1

  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 1.0

  acc_lim_theta: 0.25
  acc_lim_x: 0.5
  acc_lim_y: 0.0
  
  path_distance_bias: 2.0             
  goal_distance_bias: 0.8            
  occdist_scale: 0.01
  
  heading_lookahead: 0.325             
  heading_scoring: false              
  heading_scoring_timestep: 5.0

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2

# Differential-drive robot configuration
  holonomic_robot: false

# Forward Simulation Parameters
  sim_time: 1.5
  vx_samples: 10
  vtheta_samples: 20
  sim_granularity: 0.025
